gitlab:
  url: http://172.16.18.101
  token: 5xVvXGoDpeNSEjMUe7yZ
  group: nisp
  projects:
  - nisp-web
  - nisp-etl
  - nisp-ctl
  excludeUsers:
  - tongxin
  - sonar
  - ghost
  - root
  - yanli
  - 许魁
  - xukui
  - nisp
  - zhouty
  - pengyong
  - rengd
  - xieqiugen
  - liliang
spring:
  datasource:
    druid:
      connection-init-sqls: ["SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"]
      initial-size: 5
      max-active: 30
      min-idle: 5
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 500
      url: jdbc:mysql://127.0.0.1:3306/gitlab?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 60000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


debug: false
