gitlab:
  url: http://172.16.18.100
  token: EE8df9G5brV2LzRVxV2j
  group: rdcenter
  projects:
    - sine
  excludeUsers:
    - tongxin
    - sonar
    - ghost
    - root
    - yanli

spring:
  datasource:
    druid:
      connection-init-sqls: ["SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"]
      initial-size: 5
      max-active: 30
      min-idle: 5
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 500
      url: jdbc:mysql://172.16.116.129:3306/gitlab?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Gn@123456
      driver-class-name: com.mysql.jdbc.Driver
      max-wait: 60000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update




debug: false
