gitlab:
  url: http://172.16.18.101
  token: 5xVvXGoDpeNSEjMUe7yZ
  group: nisp
  excludeUsers:
    - tongxin
    - sonar
    - ghost
    - root
    - yanli

spring:
  datasource:
    druid:
#      connection-init-sqls: ["SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci"]
      initial-size: 5
      max-active: 30
      min-idle: 5
      filter:
        stat:
          merge-sql: true
          slow-sql-millis: 500
      url: jdbc:h2:mem:dbtest?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: org.h2.Driver
      max-wait: 60000
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    platform: h2


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
debug: false
