gitlab:
    url: http://192.168.3.34
    token: FMKwcwLZoLyBWGEXJxiG
    groups: nisp

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/gitlab?useSSL=false
        username: root
        password: 123456
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
